/* eslint-disable */
// THIS FEATURE-FLAG FILE IS AUTOGENERATED,
//  REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING
import 'quasar/dist/types/feature-flag.d.ts'

declare module 'quasar/dist/types/feature-flag.d.ts' {
  interface QuasarFeatureFlags {
    store: true
  }
}
